apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-lb
  annotations:
    'service.beta.kubernetes.io/azure-load-balancer-internal': 'true'
    'service.beta.kubernetes.io/azure-load-balancer-internal-subnet': lbs_dev
spec:
  type: LoadBalancer
  loadBalancerIP: 10.30.128.5
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  ports:
    - appProtocol: prometheus.io/metrics
      name: prometheus
      port: 15692
      protocol: TCP
      targetPort: 15692