---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: as4-message-service
  namespace: monitoring
  labels:
    release: thuega-as4-dev-monitoring
spec:
  endpoints:
  - targetPort: 8080
    scheme: http
    path: /aep-as4-message-service/actuator/prometheus
    interval: 15s
    scrapeTimeout: 14s
  selector:
    matchLabels:
      app.kubernetes.io/name: as4-message-service
  namespaceSelector:
    any: true