---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crl-downloader
  namespace: monitoring
  labels:
    release: thuega-as4-dev-monitoring
spec:
  endpoints:
  - targetPort: 8080
    scheme: http
    path: /aep-crl-downloader/actuator/prometheus
    interval: 15s
    scrapeTimeout: 14s
  selector:
    matchLabels:
      app.kubernetes.io/name: crl-downloader
  namespaceSelector:
    any: true