apiVersion: v1
kind: Service
metadata:
  name: crl-downloader-lb
  annotations:
    'service.beta.kubernetes.io/azure-load-balancer-internal': 'true'
    'service.beta.kubernetes.io/azure-load-balancer-internal-subnet': AKS-Loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.28.128.9
  selector:
    app.kubernetes.io/name: crl-downloader
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080