apiVersion: v1
kind: Service
metadata:
  name: prometheus-agent-service
  namespace: prometheus-agent
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090