apiVersion: v1
kind: Secret
metadata:
  name: solr-backup-secret
  namespace: thuega-as4-production
type: Opaque
stringData:
  username: solr-p-admin
  password: -OtZqh2TwFSmUkY2vFVL_Gc33YcWzk2OdVsY4yGHxm
