name: Update Helm Dependencies on Change 

on:
  push:
    paths:
      - 'prod/deployment/Chart.yaml'
concurrency:
  group: dependency-update
jobs:
  helm_commands:
    runs-on: ubuntu-latest

    steps:
    - name: call helm dependency update script
      uses: arvato-energy-platform/.github/actions/update_helm_dependencies@helm-dependency-update
      with:
        chart-folder: 'prod/deployment'
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_URL: devnortheuropemgmtacr.azurecr.io